CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name    VARCHAR(30)                                         NOT NULL,
    surname VARCHAR(50)                                         NOT NULL,
    email   VARCHAR(100)                                        NOT NULL UNIQUE,
    age     INTEGER                                             NOT NULL,
    gender  VARCHAR(40)                                         NOT NULL
);