CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name    VARCHAR(30)                                         NOT NULL,
    surname VARCHAR(50)                                         NOT NULL,
    email   VARCHAR(100)                                        NOT NULL UNIQUE,
    age     INTEGER                                             NOT NULL,
    gender  VARCHAR(40)                                         NOT NULL,
    created TIMESTAMP                                           NOT NULL
);

CREATE TABLE IF NOT EXISTS posts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title   VARCHAR(200)                                        NOT NULL,
    content VARCHAR(10000)                                      NOT NULL,
    author  BIGINT                                              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP                                           NOT NULL,
    edited  BOOLEAN                                             NOT NULL,
    views   BIGINT                                              NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    author  BIGINT                                              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post    BIGINT                                              NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    text    VARCHAR(500)                                        NOT NULL,
    created TIMESTAMP                                           NOT NULL,
    edited  BOOLEAN                                             NOT NULL
);